jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      host: @Redis.Host@
      port: @Redis.port@
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        maxTotal: 50
        minIdle: 5
        maxIdle: 20
      password: '&8DQxjGakJ'

    TokenCache:
      type: redis
      host: @Redis.Host@
      port: @Redis.port@
      password: '&8DQxjGakJ'
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        maxTotal: 50
        minIdle: 5
        maxIdle: 20

