spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: @Mysql.pwd@
      url: jdbc:mysql://@Mysql.Host@:3306/@Mysql.database@?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false